GreenCarbon/capp/__init__.py
from flask import Flask
application = Flask(__name__)


from capp.home.routes import home
from capp.methodology.routes import methodology
from capp.carbon_app.routes import carbon_app
from capp.aboutUs.routes import aboutUs
from capp.user.routes import user

application.register_blueprint(home)
application.register_blueprint(methodology)
application.register_blueprint(carbon_app)
application.register_blueprint(aboutUs)
application.register_blueprint(user)

GreenCarbon/capp/aboutUs/routes.py
from flask import Flask, render_template, Blueprint

aboutUs = Blueprint('aboutUs', __name__)


@aboutUs.route('/aboutUs')
def aboutUs_home():
    return render_template('aboutUs.html', title='aboutUs')

GreenCarbon/capp/carbon_app/routes.py
from flask import Flask, render_template, Blueprint

carbon_app = Blueprint('carbon_app', __name__)

@carbon_app.route('/carbon_app')
def carbon_app_home():
    return render_template('carbon_app.html', title='carbon_app')

GreenCarbon/capp/home/routes.py
from flask import Flask, render_template, Blueprint

home = Blueprint('home', __name__)

@home.route('/')
@home.route('/home')
def home_home():
  return render_template('home.html')

GreenCarbon/capp/methodology/routes.py
from flask import Flask, render_template, Blueprint

methodology = Blueprint('methodology', __name__)

@methodology.route('/methodology')
def methodology_home():
  return render_template('methodology.html', title='methodology')

GreenCarbon/capp/user/routes.py
from flask import Flask, render_template, Blueprint

user = Blueprint('user', __name__)


@user.route('/register')
def register_home():
    return render_template('register.html')

@user.route('/login')
def login_home():
    return render_template('login.html')

GreenCarbon/capp/templates/aboutUs.html
{% extends "layout.html" %}
{% block content %}
  
<!-- Header -->
<section class="section_header_home_video">
      <video class="header-video" autoplay muted loop playsinline>
          <source src="{{ url_for('static', filename='icons/AboutUs.mp4') }}" type="video/mp4">
      </video>
</section>

<!-- Developers -->
<section class="section_developers">
  <div class="container">

    <div class="developers" style="display:block;">
      <h1 style="text-align:center;"> Our Team</h1>
      <p>
        Our team of economists and developers ... Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quia, ut? Praesentium quidem sunt perspiciatis doloremque fugiat nesciunt quaerat ullam, pariatur iure unde ratione ipsum adipisci repellendus, repudiandae hic sit, temporibus molestias corrupti aut soluta sequi! Architecto deleniti expedita nisi repudiandae enim eum quas odit facilis placeat neque porro, animi incidunt consectetur. Maiores ab saepe tempora, iure asperiores beatae suscipit cum ipsum, rerum doloremque reprehenderit dolorum debitis, aliquam quasi. Maiores corporis fuga quasi nesciunt dolor iste, inventore necessitatibus unde!
      </p>      
    </div>

    <div class="developers">
        <div class="box">
          <img src="https://randomuser.me/api/portraits/men/10.jpg" alt="" style="border-radius: 50%; width:200px;">
          <h3>Developer 1</h3>
          <p>  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia repellat omnis? Odit enim hic atque dolorem iste natus inventore perspiciatis vitae dolore animi veritatis aut nemo unde similique, officia reiciendis ex architecto voluptates soluta ab tempore facilis quisquam cum.
          </p>
          <div class="container_buttons_developers">
            <a class="btn_developers" href="#"  target="_blank">Curriculum</a>
          </div> 
        </div>
        <div class="box">
          <img src="https://randomuser.me/api/portraits/women/11.jpg" alt="" style="border-radius: 50%; width:200px;">
          <h3>Developer 2</h3>
          <p>  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia repellat omnis? Odit enim hic atque dolorem iste natus inventore perspiciatis vitae dolore animi veritatis aut nemo unde similique, officia reiciendis ex architecto voluptates soluta ab tempore facilis quisquam cum.
          </p>
          <div class="container_buttons_developers">
            <a class="btn_developers" href="#"  target="_blank">Curriculum</a>
          </div> 
        </div>           
        <div class="box">
          <img src="https://randomuser.me/api/portraits/men/12.jpg" alt="" style="border-radius: 50%; width:200px;">
          <h3>Developer 3</h3>
          <p>  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia repellat omnis? Odit enim hic atque dolorem iste natus inventore perspiciatis vitae dolore animi veritatis aut nemo unde similique, officia reiciendis ex architecto voluptates soluta ab tempore facilis quisquam cum.
          </p>
          <div class="container_buttons_developers">
            <a class="btn_developers" href="#"  target="_blank">Curriculum</a>
          </div> 
        </div>     
    </div>

    <div class="developers">
      <div class="box2">
        <img src="https://randomuser.me/api/portraits/women/12.jpg" alt="" style="border-radius: 50%; width:200px;">
        <h3>Developer 4</h3>
        <p>  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia repellat omnis? Odit enim hic atque dolorem iste natus inventore perspiciatis vitae dolore animi veritatis aut nemo unde similique, officia reiciendis ex architecto voluptates soluta ab tempore facilis quisquam cum.
        </p>
        <div class="container_buttons_developers">
          <a class="btn_developers" href="#"  target="_blank">Curriculum</a>
        </div> 
      </div>
      <div class="box2">
        <img src="https://randomuser.me/api/portraits/women/13.jpg" alt="" style="border-radius: 50%; width:200px;">
        <h3>Developer 5</h3>
        <p>  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia repellat omnis? Odit enim hic atque dolorem iste natus inventore perspiciatis vitae dolore animi veritatis aut nemo unde similique, officia reiciendis ex architecto voluptates soluta ab tempore facilis quisquam cum.
        </p>
        <div class="container_buttons_developers">
          <a class="btn_developers" href="#"  target="_blank">Curriculum</a>
        </div> 
      </div>           
      <div class="box2">
        <mg src="https://randomuser.me/api/portraits/women/13.jpg" alt="" style="border-radius: 50%; width:200px;">
        <h3>Developer 6</h3>
        <p>  Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla quia repellat omnis? Odit enim hic atque dolorem iste natus inventore perspiciatis vitae dolore animi veritatis aut nemo unde similique, officia reiciendis ex architecto voluptates soluta ab tempore facilis quisquam cum.
        </p>
        <div class="container_buttons_developers">
          <a class="btn_developers" href="#"  target="_blank">Curriculum</a>
        </div> 

      </div>     
  </div>

  </div>          
</section>


{% endblock content %}

GreenCarbon/capp/templates/carbon_app.html
{% extends "layout.html" %}
{% block content %}

    <!-- Header -->
     <section class="carbon-page">
        <!-- Header -->
        <header class="page-header">
        <div>
            <h1>Carbon App <span style="color:teal"> Calculator </span></h1>
        </div>
        </header>

        <div class="wrapper">
        
            <!---------Update-------->
            <section class="update">
                <div>
                    <p>Add a new entry:</p>
                    <a class="button" type="submit"><i class="fa-solid fa-car"></i>Car</a>
                    <a class="button" type="submit"><i class="fa-solid fa-bus"></i>Bus</a>
                    <a class="button" type="submit"><i class="fa-solid fa-plane"></i>Plane</a>
                    <a class="button" type="submit"><i class="fa-solid fa-ferry"></i>Ferry</a>
                    <a class="button" type="submit"><i class="fa-solid fa-motorcycle"></i>Motorbike</a>
                    <a class="button" type="submit">Electric scooter</a>
                    <a class="button" type="submit"><i class="fa-solid fa-bicycle"></i>Bicycle</a>
                    <a class="button" type="submit"><i class="fa-solid fa-person-walking"></i>Walk</a>
                </div>

            </section>

            <!--------Alternative------->
            <section class="alternative"> 
                <h3> Smart Alternative</h1>

            <div class="recAlt"> 
                <h5> Recommended alternative</h3>
            </div>

            

            </section>
        </div>

</section>
    
{% endblock content %}

GreenCarbon/capp/templates/home.html
{% extends "layout.html" %}
{% block content %}

<!-- Header -->
<section class="section_header_home_video">
      <video class="header-video" autoplay muted loop playsinline>
          <source src="{{ url_for('static', filename='icons/HomePageVideo.mp4') }}" type="video/mp4">
      </video>
</section>

<!--Facts-->
<section class="key_figures">

  <div class="facts_container">

    <div class="key_figures_top">
      <h3> Key figures 2026</h3>
    </div>

    <div class="stats">
      <div class="stat">
        <div class="stat-number">1,843</div>
        <div class="stat-label">COLLEAGUES</div>
        
      </div>

      <div class="stat">
        <div class="stat-number">1,843</div>
        <div class="stat-label">COLLEAGUES</div>

      </div>
      <div class="stat">
        <div class="stat-number">1,843</div>
        <div class="stat-label">COLLEAGUES</div>

      </div>

    </div>
    
  </div>
</section>


   
{% endblock content %}

GreenCarbon/capp/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
      <!-- Font Awesome code -->
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />

      <!--Import the Bootstrap CSS file -->
      <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
      />
      <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css"
      />

      
      <!-- CSS code -->
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='layout.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='home.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='carbon_app.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='methodology.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='register.css') }}">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='login.css') }}">

      <!-- To activate media queries in devices -->
      <meta name="viewport" content="user-scalable=yes, width=device-width, initial-scale=1">

        {% if title %}
            <title>{{ title }}</title>
        {% else %}
            <title>home</title>
        {% endif %}
        
    </head>
    <body>
        <section class="section_navbar">
         <div class="container"> 
            <div class="navbar">
              <h1 class="logo">
                <span class="text-logo" style="color:teal"><i class="fa-solid fa-leaf"></i> Carbon</span> App
              </h1>
              <nav>
                <ul>
                    <li>
                        <a href="{{url_for('home.home_home')}}">Home</a>
                    </li>
                    <li>
                        <a href="{{url_for('methodology.methodology_home')}}">Methodology</a>
                    </li>
                    <li>
                        <a href="{{url_for('carbon_app.carbon_app_home')}}">Carbon App</a>
                    </li>
            
                    <li>
                      <a href="{{url_for('aboutUs.aboutUs_home')}}">About Us</a>
                    </li>
                    <li>
                        <a href="{{url_for('user.register_home')}}">Register</a>
                    </li>
                    <li>
                        <a href="{{url_for('user.login_home')}}">Login</a>
                    </li>
                    
                </ul>
              </nav> 
           </div>
          </div>
        </section>

        {% block content %} {% endblock %}

        <section class="section_footer">
          <div class="container">


            <div class="footer">
              <h1>
                Carbon App 
                <a href="#">
                  <i class="fa-solid fa-circle-up" style="color: #568c63"></i>
                </a>
              </h1>
              
              <!-- Venstre -->
            <div class="footer_brand">
              <p>Quick links:</p>
              <ul>
              <li>
                <a href="{{url_for('methodology.methodology_home')}}">Methodology</a>
              </li>
              <li>
                <a href="{{url_for('carbon_app.carbon_app_home')}}">Carbon App</a>
              </li>
              <li>
                <a href="{{url_for('aboutUs.aboutUs_home')}}">About Us</a>
              </li>
              <li>
                <a href="{{url_for('user.register_home')}}">Register</a>
              </li>
              <li>
                <a href="{{url_for('user.login_home')}}">Login</a>
              </li>
              </ul>
              <p>
                We are the Carbon App, a student-founded app designed to calculate your daily transport emissions!
              </p>
            </div>

            <!-- Bottom bar -->
            <div class="footer__bottom">
              <span style="color: black;">COPYRIGHT © CARBONGREEN </span>
            </div>


          </div>
        </section>

    </body>
</html>

GreenCarbon/capp/templates/login.html
{% extends "layout.html" %}
{% block content %}
  
<!-- Header -->
<section class="section_header_user">
    <div class="container">
    <header class="page-header">
        <form action="/submit" method="POST">
            <div class="page-center">
            <div class="input-group">
            <h3> Welcome <span style="color:teal"> back! </span></h3>
            <p>Username</p>
            <input type="email" name="email" placeholder="Enter your email" required>
            <p>Password</p>
            <input type="password" name="password" placeholder="Enter your password" required>
            <a class="button" type="submit">Log in</a>
            </div>
            </div>
        </form>
     </div>
</section> 

{% endblock content %}

GreenCarbon/capp/templates/methodology.html
{% extends "layout.html" %}
{% block content %}
  
<!-- Header -->
<section>
    <div>
  
      Methodology
      
    </div>
</section> 


{% endblock content %}

GreenCarbon/capp/templates/register.html
{% extends "layout.html" %}
{% block content %}
  
<!-- Header -->
<section class="section_header_user">
    <div class="container">
    <header class="page-header">
        <div>
            <h2> Register <span style="color:teal"> Here </span></h2>
        </div>
        <form action="/submit" method="POST">
            <div class="page-center">
            <div class="input-group">
            <h3>Welcome to our <span style="color:teal">app!</span></h3>
            <p>Username</p>
            <input type="username" name="username" placeholder="Enter your username" required>
            <p>Email</p>
            <input type="email" name="email" placeholder="Enter your email" required>
            <p>Password</p>
            <input type="password" name="password" placeholder="Enter your password" required>
            <p>Confirmation of password</p>
            <input type="password" name="password" placeholder="Confirm your password" required>
            <a class="button" type="submit">Sign up</a>
            </div>
            </div>
        </form>
     </div>
</section> 

{% endblock content %}